name: Announce Release on Mastodon

on:
  push:
    branches:
      - main
    path:
      - 'CHANGELOG.md'

permissions:
  pull-requests: read

jobs:
  post_to_mastodon:
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          changelog_file: CHANGELOG.md
      - name: Post to Mastodon
        uses: snakemake/mastodon-release-post-action@v1.2.3
        with:
          access-token: ${{ secrets.MASTODONBOT }}
          pr-title: ${{ github.event.head_commit.message }}
          message: |
            Beep, Beep - I am your friendly #Snakemake release announcement bot.
            
            There is a new release of the Snakemake executor for #SLURM on #HPC systems. Its version now is {{ version }}!
            
            Give us some time, and you will automatically find the plugin on #Bioconda and #Pypi.
            
            If you want to discuss the release, you will find the maintainers here on Mastodon!
            @rupdecat and @johanneskoester@fosstodon.org
            
            If you discover any issues, please report them on {{ issue_url }}.

            See {{ changelog }} for details. Here is the header of the changelog:
            
            ${{ steps.extract-release-notes.outputs.release_notes }}
            